version: '3'

volumes:
  data:
    driver: local

networks:
  autocardnet:
    driver: bridge

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "example"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autocardnet

  unstructured:
    image: quay.io/unstructured-io/unstructured-api:latest
    restart: always
    ports:
      - "4000:4000"
    command:
      - "--port"
      - "4000"
      - "--host"
      - "0.0.0.0"
    networks:
      - autocardnet

  api:
    image: lalitmishra/autocards-api:0.0.4
    build: ./api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
      POSTGRES_HOST: db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - unstructured
    networks:
      - autocardnet
