version: '3'

volumes:
  data:
    driver: local

services:
  ui:
    build: ./ui
    restart: always
    environment:
      REACT_APP_API_URL: http://api:8000
    ports:
      - "3000:80"
    depends_on:
      - api
